# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'narola_database' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  # Authentication module for RNFirebase
  pod 'Firebase/Auth'

  #React Pods
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge',
    'Core',
    'DevSupport',
  ]

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

